---
- hosts: all
  become: yes
  tasks:
  - name: install my git
    apt:
     name: git
     state: present

  - name: install tree
    apt:
       name: tree
       state: present

  - name: install wget
    apt:
     name: wget
    state: present
